import fs from 'node:fs';
import path from 'node:path';

export function writeI18nWorkflowReadme(rootDir: string): void {
	const readmePath = path.join(rootDir, 'i18n', 'README.generated.md');
	const contents = [
		'# I18n Workflow',
		'',
		'This file is generated by the local i18n workflow scripts.',
		'',
		'- `pnpm run sync:package-nls` / `pnpm run sync:webview-nls` refresh extraction outputs.',
		'- `pnpm run promote:package-nls:zh-cn` / `pnpm run promote:webview-nls:zh-cn` promote approved translations into authority.',
		'- `pnpm run generate:package-nls` / `pnpm run generate:webview-nls` generate localized artifacts from authority.',
		'',
	].join('\n');

	fs.writeFileSync(readmePath, contents, 'utf8');
}
